### ISSUE TITLE
Release todo list

### ISSUE THREAD

**Issue by ChrisAdderley** [post-kerbin-mining-corporation/FarFutureTechnologies#103]
- [ ] Balance
  - [x] Fission Z-pinch #s
  - [x] Cost
  - [x] Charge rates and powers (document)
  - [x] Tank mass ratio check
  - [x] Integrated look at overall balance
- [ ] Validate SystemHeat integration
  - [x] Check outlet temps of all engines
  - [x] Check and document heat production of all engines
  - [x] Lifecycle mass penalty analysis. 
- [x] Validate Waterfall integration
  - [x] Test all FX with latest version of shaders
- [x] Validate SpaceDust integration
  - [x] Update configs
  - [x] Consistent balance
